/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sslBT_SSLClientBT */

#ifndef _Included_sslBT_SSLClientBT
#define _Included_sslBT_SSLClientBT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sslBT_SSLClientBT
 * Method:    sendSecuredCommandBT
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sslBT_SSLClientBT_sendSecuredCommandBT
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
